### ISSUE TITLE
Is there any way to have dynamic links?

### ISSUE THREAD

**Issue by yuriybelike** [NickKaramoff/shareon#11]
Is there a way to re-run shareon after changing the `data-` attributes?

**Comment by NickKaramoff** [comment]
Like for example after changing the `data-title`? In moment there is no such possibility, but it's a nice idea to consider implementing. I'll update you on this towards the end of the week

**Comment by NickKaramoff** [comment]
This feature is now being implemented in #14 

The only thing left for me to do is to update the docs; then the update will be live!

**Comment by NickKaramoff** [comment]
Released with [v1.3.0](https://github.com/NickKaramoff/shareon/releases/tag/v1.3.0) :tada: Check the "Initialization" section in the docs for more info!

**Comment by onigetoc** [comment]
How can we do that, Re-run shareon?
Because on javascript url rewrite and title.

**Comment by NickKaramoff** [comment]
> How can we do that, Re-run shareon?

@onigetoc just run `shareon()`. This function is being exposed to the DOM.

**Comment by onigetoc** [comment]
I used the no-init version and it work now.

**Comment by NickKaramoff** [comment]
> I used the no-init version and it work now.

That's strange, it should work with the default (autoinit) version too.
