### ISSUE TITLE
Fix Messenger button not working with hardcoded `app_id`

### ISSUE THREAD

**Issue by deoomen** [NickKaramoff/shareon#17]
Sharing via Messenger button seems to be broken due to hardcoded Facebook `app_id` property.
If you try to share any url via Messenger there will be always an error page.
Maybe add data atribute with custom `app_id`?

```html
<a class="messenger" data-key="<custom_app_id>"></a>
```

**Comment by NickKaramoff** [comment]
Oh wow really, I guess I did not really understand this app thing that Messenger does 😄 I'll get it done by the end of the week 👍

**Comment by divyajyotiuk** [comment]
I don't think because it's hardcoded. I think the app_id has expired.

**Comment by NickKaramoff** [comment]
What I understood for now is that my app requires me to add every single domain shareon will be used at, I guess. In any case, I think I need to create ToS and a Privacy Policy, which I have no idea how they even apply here — I don't collect any data 🤷‍♂️ I am really struggling with this 😅 

For now, I'll implement a `data-app-id` element for Messenger and maybe I'll figure out how this works. I mean, ShareThis and AddThis do get this to work...

**Comment by NickKaramoff** [comment]
Sorry for the long wait — I am in the middle of my exams right now 🙄 I hope the fix will be ready around Sep 16th 🙏

**Comment by NickKaramoff** [comment]
Sorry that it took so long — the [v1.6.0](https://github.com/NickKaramoff/shareon/releases/tag/v1.6.0) now supports the `data-fb-app-id` attribute for the Messenger button. The docs were updated accordingly.
