### ISSUE TITLE
Make WhatsApp button work for WhatsApp Web

### ISSUE THREAD

**Issue by divyajyotiuk** [NickKaramoff/shareon#18]
The link provided for whatsapp only seems to open on mobile and is blank if open it on desktop browser.

**Comment by NickKaramoff** [comment]
This is because a custom protocol is used. The link works if you have a WhatsApp app installed on your computer. I'll change it to a `https://wa.me` URL to try to make it work in WhatsApp Web. Should be done by Monday

**Comment by NickKaramoff** [comment]
Sorry that it takes so long; I am preparing for my last exam this semester 📚 I hope to implement it by 16-09-2020
