### ISSUE TITLE
css file not minified

### ISSUE THREAD

**Issue by krzyko** [NickKaramoff/shareon#22]
Good day,
file shareon.min.css released within 1.4.4 version is not minified.
Regards,
Krzysztof Kosz.

**Comment by NickKaramoff** [comment]
Got it, I'm on it 🕶️

**Comment by NickKaramoff** [comment]
Fixed in [v1.4.5](https://github.com/NickKaramoff/shareon/releases/tag/v1.4.5) :tada:
