### ISSUE TITLE
add linkedin icon

### ISSUE THREAD

**Issue by krzyko** [NickKaramoff/shareon#5]
It would be nice to add LinkedIn share button. LinkedIn share url looks like:
https://www.linkedin.com/shareArticle?url=https%3A%2F%2Fhttps://shareon.js.org/%2F&mini=true

and the svg path converted from Likely to 24x24 viewport is below:
`data:image/svg+xml;charset=utf-8,%3Csvg fill='%23fff' viewBox='0 0 24 24' xmlns='http://www.w3.org/2000/svg'%3E%3Cpath d='M3.6,9L7.2,9L7.2,20.4L3.6,20.4L3.6,9ZM5.4,3.3C6.6,3.3 7.5,4.2 7.5,5.4C7.35,6.45 6.45,7.5 5.4,7.5C4.2,7.5 3.3,6.45 3.3,5.4C3.3,4.2 4.2,3.3 5.4,3.3M9.3,9L12.75,9L12.75,10.5C13.5,9.3 14.85,8.7 16.2,8.7C19.8,8.7 20.4,11.1 20.4,14.1L20.4,20.4L16.8,20.4L16.8,14.85C16.8,13.5 16.8,11.85 15,11.85C13.2,11.85 12.9,13.35 12.9,14.85L12.9,20.55L9.3,20.55L9.3,9ZM19.5,0L4.5,0C1.5,0 0,1.5 0,4.5L0,19.5C0,22.5 1.5,24 4.5,24L19.5,24C22.5,24 24,22.5 24,19.5L24,4.5C24,1.5 22.5,0 19.5,0Z'/%3E%3C/svg%3E`

Background color is #1576B2 in hex.

May thanks. If that would be easier I can try to prepare pull request.

**Comment by NickKaramoff** [comment]
Thank you for your feature request! I'll get the button ready in a few hours

**Comment by NickKaramoff** [comment]
Released with [v1.2.0](https://github.com/NickKaramoff/shareon/releases/tag/v1.2.0) 🎉

**Comment by krzyko** [comment]
Once again - many thanks.
